config/routes.rb
Rails.application.routes.draw do
  devise_for :users
resources :posts
resources :projects
resources :contacts, only: [:new, :create]

get 'welcome/index'
root 'welcome#landing'

get '*path' => redirect('/')
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,  :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  attribute :message, :validate => true
  attribute :nickname, :captcha => true

  def headers
  {
    :subject => "Contact Form",
    :to => "codycondon50@gmail.com",
    :from => %("#{name}" <#{email}>)
  }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message'
      render 'new'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 8)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params

    if @post.save
      redirect_to @post, notice: "Post created! The article was successfully saved"
    else
      render 'new', notice: "Oh no, Unable to save the post"
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def update
    if @post.update post_params
      redirect_to @post, notice: "Your article was sucessfully updated"
    else
      render 'edit'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :slug)
  end

  def find_post
    @post = Post.friendly.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @projects = Project.all.order("created_at desc")
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params

    if @project.save
      redirect_to @project, notice: "Project successfully saved Cody!"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update project_params
      redirect_to @project , notice: "Hey Cody, your project was successfully updated! "
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end



  private

  def find_project
    @project = Project.friendly.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :link, :slug)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @posts = Post.all.limit(3).order("created_at desc")
    @projects = Project.all.limit(3).order("created_at desc")
  end

  def landing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code,language)
      Pygments.highlight(code, lexer: language)
    end
  end
  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">Say Hello!</h1>

<div class="skinny_wrapper wrapper_padding">
  <h1>Thank you for your message!</h1>
  <p>I'll get back to you asap</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page_title">Contact me</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= form_for @contact do |f| %>

  <%= f.label :name %> <br>
  <%= f.text_field :name, required: true %>

  <br>

  <%= f.label :email %> <br>
  <%= f.email_field :email, required: true %>

  <br>

  <%= f.label :message %> <br>
  <%= f.text_area :message, as: :text %>

  <div class="hidden">
    <%= f.label :nickname %> <br>
    <%= f.text_field :nickname, hint: 'leave this field blank' %>
   </div>

   <%= f.submit 'Send Message', class: "button" %>
<%end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cody Condon Full-Stack Web Developer </title>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
   <link rel="icon" href="faviconwebsite.png">
  <meta name="viewport" content="initial-scale=1">
</head>
<body>
  <header id="main_navigation" class="clearfix">
    <%= link_to "Cody Condon", welcome_index_path, class: "name" %>

  <nav class="navbar">
    <%= link_to "Projects", projects_path, class: "nav1" %>
    <%= link_to "Thoughts", posts_path, class: "nav2" %>
    <%= link_to "Contact", new_contact_path, class: "nav3" %>
    <% if user_signed_in? %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    <%end %>
  </nav>
</header>
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% elsif alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

<%= yield %>

  <footer id="main_footer">
    <p class="copyright">&copy;2016 Cody Condon</p>
    <nav>
      <a href="https://www.instagram.com/codycondon_"target="_blank"><i class="fa fa-instagram"></i></a>
      <a href="https://github.com/codycc" target="_blank"><i class="fa fa-github-alt"></i></a>
      <a href="https://ca.linkedin.com/in/codycondon" target="_blank"><i class="fa fa-linkedin"></i></a>

    </nav>
  </footer>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <h2><%=pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>
  <%= f.label :title %> <br>
  <%= f.text_field :title %>

  <br>
  <br>

  <%= f.label :content, "Write your article here" %> <br>
  <%= f.text_area :content %>

  <br>
  <br>

  <%= f.submit %>


<% end %>

app/views/posts/edit.html.erb
<h1 id="page_title">Edit Post</h1>

<div class="skinny_wrapper wrapper_padding">
<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1 id="page_title">My Thoughts</h1>

<div id="posts_wrapper" class="skinny_wrapper">
  <% @posts.each do |post| %>
    <div class="post">
        <p class="date"><%= post.created_at.strftime('%A, %B %d') %></p>
        <h2><a href=""><%= link_to post.title, post %></a></h2>
        <hr>
    </div>
  <% end %>
 </div>

 <%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1 id="page_title">New Post</h1>

<div class="skinny_wrapper wrapper_padding">
<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
<header>
    <p class="date"><%= @post.created_at.strftime('%A, %B, %d') %></p>
  <h1><%= @post.title %></h1>
  <hr>
</header>

<div id="content">
  <%= markdown @post.content %>
</div>
 <% if user_signed_in? %>
  <div id="admin_links">
    <%= link_to "Edit article", edit_post_path(@post) %>
    <%= link_to "Delete article", post_path(@post), method: :delete, data: { confirm: "Are you sure?"} %>
  </div>
 <% end %>
<hr>

  <div id="share_box">
    <p>CODY CONDON</p>
  </div>

  <hr>

</div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
  <h2><%=pluralize(@project.errors.count, "error") %> prevented this post from saving:</h2>
  <ul>
    <% @project.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>
  <%= f.label :title %> <br>
  <%= f.text_field :title %>

  <br>
  <br>

  <%= f.label :desription %> <br>
  <%= f.text_area :description %>

  <br>
  <br>

  <%= f.label :link %> <br>
  <%= f.text_field :link %>

  <%= f.submit %>


<% end %>

app/views/projects/edit.html.erb
<h1 id="page_title">Edit Project</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page_title">Projects</h1>

<div id="posts_wrapper" class="skinny_wrapper">
  <% @projects.each do |project| %>
    <div class="post">
        <p class="date"><%= project.created_at.strftime('%A, %B %d') %></p>
        <h2><a href=""><%= link_to project.title, project %></a></h2>
        <hr>
    </div>
  <% end %>
 </div>

app/views/projects/new.html.erb
<h1 id="page_title">New Project</h1>

<div class="skinny_wrapper wrapper_padding">

  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
<header>
    <p class="date"><%= @project.created_at.strftime('%A, %B, %d') %></p>
  <h1><%= @project.title %></h1>
  <hr>
</header>

<div id="content">
  <div id="innercontent">
  <%= markdown @project.description %>
  </div>
  <div class="button_wrapper">
    <a href="<%= @project.link %>" class="project_button" target="_blank">Visit <%= @project.title %></a>
  </div>
</div>

  <% if user_signed_in? %>
   <div id="admin_links">
     <%= link_to "Edit Project", edit_project_path(@project) %>
     <%= link_to "Delete Project", project_path(@project), method: :delete, data: { confirm: "Are you sure?"} %>
   </div>
  <% end %>


<hr>
</div>

app/views/welcome/index.html.erb
<body id="welcome_index_page">
<div class="wrapper wrapper_padding clearfix">
    <div class="col-1 about homepage_content">
      <h2>About</h2>
      <hr>
      <p>I am here to create that stunning user experience for
         clients.</p>
      <p>Have over 2 years experience with HTML/CSS,
         Javascript and responsive design.
         Currently focusing on React.js with knowledge of
          Ruby on Rails. </p>

      <p> Coming from a strong background of marketing,
         design and music. I've worked with various
         major record labels, teaming with their artists.
        Whom I met with and wrote for accordingly
        depending on the individuals image and
        perspective on music. </p>
        <p> You can find me on <a href="https://instagram.com/codycondon_" target="_blank">Instragram</a>, posting pictures
          mostly music related,on my <a href="https://github.com/codycc" target="_blank">Github</a> where I'm pushing daily
          as well as <a href="https://ca.linkedin.com/in/codycondon" target="_blank">linkedIn</a>. Feel free to connect</p>
    </div>

    <div class="col-2 homepage_content">
      <h2>Projects</h2>
      <hr>
      <% @projects.each do |project| %>
          <h3><a href="#"><%= link_to project.title, project %></a></h3>
          <p class="date"><%= project.created_at.strftime("%A, %b %d")%></p>
      <%end%>

    </div>

    <div class="col-3 homepage_content">
      <h2>Thoughts</h2>
      <hr>
      <% @posts.each do |post| %>
          <h3><a href="#"><%= link_to post.title, post %></a></h3>
          <p class="date"><%= post.created_at.strftime("%A, %b %d")%></p>
      <%end%>
    </div>


  </div>
</body>

app/views/welcome/landing.html.erb
<body class="welcome_body">
  <div class="skinny_wrapper wrapper_padding welcome_page">
      <h1>Full Stack Developer</h1><br>
      <h1><a> <%= link_to "Welcome", welcome_index_path%></a></h1>
  </div>

</body>
<div class="landingphoto">
</div>